auth:
  apikey: "![W+TfeTPaui0cpB1MAmEPiNkknF1nvbRqLRBzXbglpuomRNEeZlt5WkIV2U97LFcx]"
  
http:
  port: "8081"
  
serviceNow:
  port: "8087"
  host: "0.0.0.0"
  protocol: "HTTP"
  clientId: "452e961bff2c4e899f09a3afb5ffa099"
  clientSecret: "5447C65c460F4a9583f632B26C3c6c7a"
  
autoD:
  apiID: "16972094"